
paradecision:
  database:
    encryption:
      key: --

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: --
    username: --
    password: --
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    serialization:
      fail-on-empty-beans: false

jwt:
  secret: --
  expiration: 604800000
